# This is a config for E2B sandbox template.
# You can use template ID (5pykcqq1xjre32wfy8yr) or template name (vibe-nextjs-test-2-romain) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("vibe-nextjs-test-2-romain") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-nextjs-test-2-romain") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-nextjs-test-2-romain')

team_id = "c24b7f95-aefd-488f-9129-520723632887"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-nextjs-test-2-romain"
template_id = "5pykcqq1xjre32wfy8yr"
